### ISSUE TITLE
Critical error on activate plugin

### ISSUE THREAD

**Issue by muggsy0011** [pressidium/pressidium-cookie-consent#1]
When installing and activating plugin there is critical error notice. 
Installation was on fresh instance of wordpress (version 6.2.2.), with no plugins installed.

Installing with zip file.

Error Details
=============
An error of type E_COMPILE_ERROR was caused in line 53 of the file /home/devpabnu/public_html/test/wp-content/plugins/pressidium-cookie-consent-master/pressidium-cookie-consent.php. Error message: require_once(): Failed opening required '/home/devpabnu/public_html/test/wp-content/plugins/pressidium-cookie-consent-master/vendor/autoload.php' (include_path='.:/opt/alt/php74/usr/share/pear')

**Comment by muggsy0011** [comment]
Uh, sorry, didnt know there is plugin also in plugin directory.

Thank you for your help, keep up superb work!

Regards M

**Comment by over-engineer** [comment]
Thanks for the kind words! I’m closing this issue as resolved. If you have any more questions, feel free to ask :slightly_smiling_face:
