### ISSUE TITLE
Cookies tab not showing up in Brave browser

### ISSUE THREAD

**Issue by opicron** [pressidium/pressidium-cookie-consent#101]
**Describe the bug**
Apparently Brave browser has a user agent css rule which hides the Cookies tab in the settings.

**Steps to reproduce**
Use the web element inspector (F12) in Brave and view the tab-cookies html. It will show an user agent style which hides the tab with the !important addition.

**Expected behavior**
Expected behaviour is to see the Cookies tab.

**Screenshots**
![image](https://github.com/user-attachments/assets/f2e2763c-ac65-4930-9970-65dc85994151)

**Environment (please complete the following information):**
 - Browser: Brave Version 1.73.91 Chromium: 131.0.6778.85 (Official Build) (64-bit)
 - Plugin version: Latest
 - WordPress version: 6.7.1
 - PHP version: 7.4

**Checklist**
* [x] I have searched the [GitHub issues](https://github.com/pressidium/pressidium-cookie-consent/issues) to ensure this is not a duplicate
* [x] I have provided sufficient information to reproduce and understand the issue
* [x] I have tested the issue using the latest version of the plugin
* [x] I have included any relevant error messages, logs, or screenshots
* [x] I have reviewed the [wiki](https://github.com/pressidium/pressidium-cookie-consent/wiki) to ensure this issue is not related to a misconfiguration

**Comment by over-engineer** [comment]
Hey, @opicron!

Thank you for taking the time to report this! We'll address this in our next update.

**Comment by over-engineer** [comment]
This was addressed in `1.7.1` which was just released on the Plugin Directory.

@opicron Thanks once again for bringing this to our attention!

Closing as resolved.
