### ISSUE TITLE
Can't update secondary button text

### ISSUE THREAD

**Issue by joppuyo** [pressidium/pressidium-cookie-consent#2]
Hey! Thanks for this great plugin. It's exactly what I was looking for.

However, I noticed that there's an issue where the secondary button text cannot be changed. The secondary button overwrites the primary button text when text is entered in the field.

It looks like there is a typo in this file: https://github.com/pressidium/pressidium-cookie-consent/blob/a14cc38d78e0f06863f2408a1f05c9a178bb342c/src/admin/store/reducer.js#L334

So it should be relatively easy to fix.

**Comment by over-engineer** [comment]
Hey, @joppuyo!

Thank you for your kind words and for spotting that issue! We appreciate you taking the time to report it.

The issue was fixed in `1.0.2`, which was just released on the Plugin Directory.

**Comment by joppuyo** [comment]
I updated to the latest version and now I can update the button text as expected. Thank you for the fast response!
