### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by partner4** [pressidium/pressidium-cookie-consent#22]
Dears. I found your plugin and it is great, simple and yet powerful. 
I noticed one bug. On Translate Cookie table headers translations are not saved properly and shows as undefined.

Also it would be great to have a modal window for change settings after confirming consent.
Something like this
![Untitled-1](https://github.com/pressidium/pressidium-cookie-consent/assets/141438704/9a6c5dd0-f312-4ec2-bf68-a9ff8d7ebb68)

Here is my database record
a:17:{s:7:"autorun";b:1;s:13:"force_consent";b:0;s:17:"autoclear_cookies";b:0;s:12:"page_scripts";b:0;s:14:"hide_from_bots";b:1;s:9:"reconsent";b:1;s:5:"delay";i:0;s:17:"cookie_expiration";i:182;s:11:"cookie_path";s:1:"/";s:13:"cookie_domain";s:16:"test7.partner.si";s:13:"auto_language";s:7:"browser";s:11:"cookie_name";s:25:"pressidium_cookie_consent";s:9:"languages";a:2:{s:2:"en";a:2:{s:13:"consent_modal";a:4:{s:5:"title";s:14:"Cookie Consent";s:11:"description";s:219:"Hi, we use cookies to ensure the website's proper operation, to analyze traffic and performance, and to provide social media features.  <button type="button" data-cc="c-settings" class="cc-link">Cookie Settings</button>";s:11:"primary_btn";a:2:{s:4:"text";s:10:"Accept all";s:4:"role";s:10:"accept_all";}s:13:"secondary_btn";a:2:{s:4:"text";s:16:"Accept necessary";s:4:"role";s:16:"accept_necessary";}}s:14:"settings_modal";a:7:{s:5:"title";s:18:"Cookie preferences";s:17:"save_settings_btn";s:13:"Save settings";s:14:"accept_all_btn";s:10:"Accept all";s:14:"reject_all_btn";s:10:"Reject all";s:15:"close_btn_label";s:5:"Close";s:20:"cookie_table_headers";a:5:{i:0;a:1:{s:4:"name";s:4:"Name";}i:1;a:1:{s:6:"domain";s:6:"Domain";}i:2;a:1:{s:10:"expiration";s:10:"Expiration";}i:3;a:1:{s:4:"path";s:4:"Path";}i:4;a:1:{s:11:"description";s:11:"Description";}}s:6:"blocks";a:5:{i:0;a:2:{s:5:"title";s:22:"Cookie usage &#x1f4e2;";s:11:"description";s:339:"We use cookies to ensure the website's proper operation, to analyze traffic and performance, and to provide social media features. Click on the different category headings to find out more and change our default settings. However, blocking some types of cookies may impact your experience of the site and the services we are able to offer.";}i:1;a:4:{s:5:"title";s:26:"Strictly necessary cookies";s:11:"description";s:212:"These cookies are necessary for the website to function and cannot be switched off in our systems. You can set your browser to block or alert you about these cookies, but some parts of the site may not then work.";s:6:"toggle";a:3:{s:5:"value";s:9:"necessary";s:7:"enabled";b:1;s:8:"readonly";b:1;}s:12:"cookie_table";a:0:{}}i:2;a:4:{s:5:"title";s:33:"Performance and Analytics cookies";s:11:"description";s:226:"These cookies allow us to analyze visits and traffic sources so we can measure and improve the performance of our site. They help us to know which pages are the most and least popular and see how visitors move around the site.";s:6:"toggle";a:3:{s:5:"value";s:9:"analytics";s:7:"enabled";b:0;s:8:"readonly";b:0;}s:12:"cookie_table";a:0:{}}i:3;a:4:{s:5:"title";s:35:"Advertisement and Targeting cookies";s:11:"description";s:344:"These cookies may be set through our site by our social media providers and/or our advertising partners. They may be used by those companies to build a profile of your interests and show you relevant adverts on other sites. They do not store directly personal information, but are based on uniquely identifying your browser and internet device.";s:6:"toggle";a:3:{s:5:"value";s:9:"targeting";s:7:"enabled";b:0;s:8:"readonly";b:0;}s:12:"cookie_table";a:0:{}}i:4;a:2:{s:5:"title";s:16:"More information";s:11:"description";s:89:"For any queries in relation to our policy on cookies and your choices, please contact us.";}}}}s:2:"sl";a:2:{s:13:"consent_modal";a:4:{s:5:"title";s:21:"Nastavitve zasebnosti";s:11:"description";s:168:"Spletno mesto uporablja piškotke za zagotavljanje najboljše uporabniške izkušnje. <button type=button data-cc=c-settings class=cc-link>Upravljaj nastavitve</button>";s:11:"primary_btn";a:2:{s:4:"text";s:10:"Dovoli vse";s:4:"role";s:10:"accept_all";}s:13:"secondary_btn";a:2:{s:4:"text";s:10:"Zavrni vse";s:4:"role";s:16:"accept_necessary";}}s:14:"settings_modal";a:7:{s:5:"title";s:21:"Nastavitve piškotkov";s:17:"save_settings_btn";s:17:"Shrani nastavitve";s:14:"accept_all_btn";s:10:"Dovoli vse";s:14:"reject_all_btn";s:10:"Zavrni vse";s:15:"close_btn_label";s:5:"Zapri";s:20:"cookie_table_headers";a:12:{i:0;a:0:{}i:1;a:0:{}i:2;a:0:{}i:3;a:0:{}i:4;a:0:{}i:5;a:0:{}i:6;a:0:{}i:7;a:1:{s:4:"name";s:0:"";}i:8;a:1:{s:6:"domain";s:0:"";}i:9;a:1:{s:10:"expiration";s:0:"";}i:10;a:1:{s:4:"path";s:0:"";}i:11;a:1:{s:11:"description";s:0:"";}}s:6:"blocks";a:5:{i:0;a:2:{s:5:"title";s:18:"Uporaba piškotkov";s:11:"description";s:392:"Piškotki so majhne besedilne datoteke, ki se namestijo na uporabnikov brskalnik ob obisku spletnega mesta. Uporabljajo se za zagotavljanje osnovnih funkcionalnosti spletnega mesta in za izboljšanje vaše spletne izkušnje. Za več podrobnosti v zvezi s piškotki in drugimi občutljivimi podatki preberite <a href='zasebnost in piskotki' target=_blank class=cc-link>politiko zasebnosti</a>.";}i:1;a:4:{s:5:"title";s:16:"Nujni piškotki ";s:11:"description";s:139:"Nujni piškotki omogočajo osnovne funkcije in so bistveni za pravilno delovanje spletnega mesta. Nujnih piškotkov ni mogoče izključiti.";s:6:"toggle";a:3:{s:5:"value";s:9:"necessary";s:7:"enabled";b:1;s:8:"readonly";b:1;}s:12:"cookie_table";a:0:{}}i:2;a:4:{s:5:"title";s:21:"Analitični piškotki";s:11:"description";s:152:"Analitični piškotki anonimno beležijo informacije o uporabi spletnega mesta in na podlagi teh informacij pomagajo izboljšati uporabniško izkušnjo.";s:6:"toggle";a:3:{s:5:"value";s:9:"analytics";s:7:"enabled";b:0;s:8:"readonly";b:0;}s:12:"cookie_table";a:0:{}}i:3;a:4:{s:5:"title";s:23:"Oglaševalski piškotki";s:11:"description";s:183:"Oglaševalski piškotki anonimno beležijo podatke o vaših obiskih spletnih strani, s pomočjo katerih vam oglaševalci prikazujejo oglase, ki so ustreznejši in zanimivejši za vas.";s:6:"toggle";a:3:{s:5:"value";s:9:"targeting";s:7:"enabled";b:0;s:8:"readonly";b:0;}s:12:"cookie_table";a:0:{}}i:4;a:2:{s:5:"title";s:19:"Dodatne informacije";s:11:"description";s:27:"Poglejte politko zasebnosti";}}}}}s:11:"gui_options";a:2:{s:13:"consent_modal";a:4:{s:6:"layout";s:3:"box";s:8:"position";s:12:"bottom right";s:10:"transition";s:5:"slide";s:12:"swap_buttons";b:0;}s:14:"settings_modal";a:3:{s:6:"layout";s:3:"box";s:8:"position";s:4:"left";s:10:"transition";s:5:"slide";}}s:18:"pressidium_options";a:5:{s:16:"primary_btn_role";s:10:"accept_all";s:18:"secondary_btn_role";s:16:"accept_necessary";s:12:"cookie_table";a:3:{s:9:"necessary";a:1:{i:0;a:6:{s:4:"name";s:13:"PH_HPXY_CHECK";s:6:"domain";s:16:"test7.aprtner.si";s:10:"expiration";s:7:"Session";s:4:"path";s:0:"";s:11:"description";s:12:"Nujni kookie";s:8:"is_regex";b:0;}}s:9:"analytics";a:0:{}s:9:"targeting";a:0:{}}s:15:"blocked_scripts";a:1:{i:0;a:3:{s:3:"src";s:0:"";s:8:"category";s:9:"analytics";s:8:"is_regex";b:0;}}s:6:"colors";a:21:{s:2:"bg";s:7:"#f9faff";s:4:"text";s:7:"#112954";s:14:"btn-primary-bg";s:7:"#3859d0";s:16:"btn-primary-text";s:7:"#f9faff";s:20:"btn-primary-hover-bg";s:7:"#1d2e38";s:16:"btn-secondary-bg";s:7:"#dfe7f9";s:18:"btn-secondary-text";s:7:"#112954";s:22:"btn-secondary-hover-bg";s:7:"#c6d1ea";s:13:"toggle-bg-off";s:7:"#8fa8d6";s:12:"toggle-bg-on";s:7:"#3859d0";s:18:"toggle-bg-readonly";s:7:"#cbd8f1";s:14:"toggle-knob-bg";s:4:"#fff";s:22:"toggle-knob-icon-color";s:7:"#ecf2fa";s:24:"cookie-category-block-bg";s:7:"#ebeff9";s:30:"cookie-category-block-bg-hover";s:7:"#dbe5f9";s:14:"section-border";s:7:"#f1f3f5";s:10:"block-text";s:7:"#112954";s:19:"cookie-table-border";s:7:"#e1e7f3";s:10:"overlay-bg";s:24:"rgba(230, 235, 255, .85)";s:19:"webkit-scrollbar-bg";s:7:"#ebeff9";s:25:"webkit-scrollbar-bg-hover";s:7:"#3859d0";}}s:8:"revision";i:2;s:7:"version";s:5:"1.1.2";}

Thanks for answer, Gregor

**Comment by over-engineer** [comment]
Hey, @partner4!

Thanks for your thoughtful words and for bringing that issue to our attention.

>I noticed one bug. On Translate Cookie table headers translations are not saved properly and shows as undefined.

The issue was fixed in `1.1.3`, which was released on the Plugin Directory a few hours ago.

>Also it would be great to have a modal window for change settings after confirming consent.

Thanks for the suggestion! We’ll definitely consider implementing it in a future version. I opened #24 to discuss this further and track its development.

In the meantime, if you’re comfortable with coding, you can build a custom button that calls [`pressidiumCookieConsent.showSettings()`](https://github.com/pressidium/pressidium-cookie-consent/wiki/Control-programmatically#showsettings) to open the settings modal. More information is available in our [wiki](https://github.com/pressidium/pressidium-cookie-consent/wiki/), under the [Control programmatically](https://github.com/pressidium/pressidium-cookie-consent/wiki/Control-programmatically) section.

**Comment by over-engineer** [comment]
This has been implemented in the latest release. The floating button is now being tracked on a separate issue. Closing as resolved.

**Comment by partner4** [comment]
Wow, 
thanks for fast response.

I can confirm that issue is resolved in current release.

Thanks again, Gregor
