### ISSUE TITLE
Message about not saving changes

### ISSUE THREAD

**Issue by anisoft2** [pressidium/pressidium-cookie-consent#25]
Great plugin but I noticed a problem.

Changes save correctly, but when exiting the plugin page, the message "Leave page? Your changes may not be saved."

WP 6.3, PHP 7.4

**Comment by over-engineer** [comment]
Hey, @anisoft2!

Thanks for taking the time to report this.

The issue was fixed in `1.1.4`, which was just released on the Plugin Directory.
