### ISSUE TITLE
Empty blocked script breaks other scripts

### ISSUE THREAD

**Issue by williarin** [pressidium/pressidium-cookie-consent#41]
Hello,

In Blocked Scripts section, if we add a row then save the form without filling a script name, it breaks the frontend because some scripts can't be loaded anymore.

A solution would be to add a `required` attribute on the input, or to automatically erase empty rows upon saving.

**Comment by over-engineer** [comment]
Hey, @williarin!

Good catch! Thanks for spotting and reporting that.

This issue was address in `1.3.0`, which was just released on the Plugin Directory.
