### ISSUE TITLE
Language detection / document - polish language

### ISSUE THREAD

**Issue by Nikodemsky** [pressidium/pressidium-cookie-consent#61]
It's regarding thing i have mentioned in forums:
https://wordpress.org/support/topic/language-detection-5/

It detects en-GB, de-DE properly, if checked from dropdown - but the issue is that for example polish language does not have any other options like those above and is not detected - probably, because translation plugins like WPML and Polylang(just checked on both) is using "pl-PL" and not only "pl"(like the value from option in dropdown) and core Wordpress itself too btw.

Changing `<html lang>` is not always possibile and by semantics not really recommended.

Here you can check full list of locales codes:
https://gist.github.com/danielbachhuber/14af08c5faac07d5c0c182eb66b19b3e

or here, more officially:
https://translate.wordpress.org/

Also by those you can see that wordpress itself is not really using "en" as locale code anywhere, so it might be good idea to switch to "en-GB" for default locale.

Hope it's doable!

**Comment by Nikodemsky** [comment]
Any ETA on fixing this?

**Comment by over-engineer** [comment]
The changes in `1.7.0` likely fixes this (PR #96)

Related issues
---

* #75
* #95

**Comment by over-engineer** [comment]
Hey, @Nikodemsky!

I'm closing this issue as resolved. Feel free to reopen it if there's anything more to address.
