### ISSUE TITLE
Missing "Reject all" button

### ISSUE THREAD

**Issue by DennisRas** [pressidium/pressidium-cookie-consent#64]
The user should be able to reject all cookies without opening the preferences/settings modal.
Either/both with a close button/icon and/or 3rd button in the button group.

~A quick suggestion would be to add a "Reject all" to the Secondary Button option array.~
![image](https://github.com/pressidium/pressidium-cookie-consent/assets/983466/bf624ffb-c089-4318-96f4-8af5ecb529c0)

Edit: Actually disregard the suggestion. I guess the "Accept necessary" option technically counts as a "No thanks" button. I just noticed that [CookieConsent v3](https://playground.cookieconsent.orestbida.com/) has 3 buttons that makes options more clear for the user.
![image](https://github.com/pressidium/pressidium-cookie-consent/assets/983466/efe04b21-0c48-4334-acb5-6649e3482b48)

**Comment by over-engineer** [comment]
Hey, @DennisRas!

>Actually disregard the suggestion. I guess the "Accept necessary" option technically counts as a "No thanks" button

Spot on. Choosing “Accept necessary” essentially translates to “Reject all”.

You could even change the button label to “Reject all”. On wp-admin, go to Cookie Consent ⭢ Translations, select the “Edit” action for the language you wish to update (e.g. “English”),  change the “SECONDARY BUTTON” from “Accept necessary” to “Reject all”.

Closing as resolved.
