### ISSUE TITLE
Cookie categories

### ISSUE THREAD

**Issue by martynastrl** [pressidium/pressidium-cookie-consent#71]
I inserted Necessary cookie and saved:
https://shottr.cc/s/KHeq/SCR-20240620-gyd.png
But it does not show up in the preview:
https://shottr.cc/s/KkRT/SCR-20240620-gz9.png

In addition, is there an option to hide cookie category, that is empty? For example Functionality and Preferences cookies?
https://shottr.cc/s/KKY2/SCR-20240620-h05.png

**Comment by over-engineer** [comment]
Hey, @martynastrl!

The two issues you brought up have been addressed.

>I inserted Necessary cookie and saved:
>https://shottr.cc/s/KHeq/SCR-20240620-gyd.png
>But it does not show up in the preview:
>https://shottr.cc/s/KkRT/SCR-20240620-gz9.png

Thanks for spotting that! We appreciate you taking the time to report it.

This was fixed in `1.5.1`, which was just released on the Plugin Directory.

>In addition, is there an option to hide cookie category, that is empty? For example Functionality and Preferences cookies?
>https://shottr.cc/s/KKY2/SCR-20240620-h05.png

We were tracking that in #55, which was implemented in `1.5.0`.

**Comment by over-engineer** [comment]
I’m closing this issue as resolved.
