### ISSUE TITLE
Can this be configured to work with other global cookie lawas like COPPA, e Privacy, POPPIA, with Geo-blocking, Do Not Track (DNT), etc? Is there a way I can achieve these with this software?

### ISSUE THREAD

**Issue by tradegong** [pressidium/pressidium-cookie-consent#73]
Can this be configured to work with other global cookie lawas like COPPA, e Privacy, POPPIA, with Geo-blocking, Do Not Track (DNT), etc? Is there a way I can achieve these with this software? I need to configure global/ regional lwa, geo-blocking, dnt, COPPA, etc, to make my website truly global. How can I go about doing this?
Thanks for your help.

**Comment by over-engineer** [comment]
Hey, @tradegong!

Our plugin allows you to display a customizable cookie consent banner to your website and conditionally load third-party scripts (analytics, performance, targeting, etc.) based on the user-selected preferences.

COPPA/POPIA/ePrivacy
---

According to the linked Wikipedia articles:

* [COPPA](https://en.wikipedia.org/wiki/Children%27s_Online_Privacy_Protection_Act): Children’s Online Privacy Protection Rule — a United States federal law. The act, effective April 21, 2000, applies to the online collection of personal information by persons or entities under U.S. jurisdiction about children under 13 years of age, including children outside the U.S. if the website or service is U.S.-based.
* [PoPIA](https://en.wikipedia.org/wiki/Protection_of_Personal_Information_Act,_2013): Protection of Personal Information Act — a piece of legislation which governs the law of data protection and privacy in South Africa
* [ePD](https://en.wikipedia.org/wiki/EPrivacy_Directive): ePrivacy Directive — an EU directive on data protection and privacy in the digital age
* [ePR](https://en.wikipedia.org/wiki/EPrivacy_Regulation): ePrivacy Regulation — a proposal for the regulation of various privacy-related topics, mostly in relation to electronic communications within the European Union. The (new) ePrivacy Regulation will repeal the (current) ePrivacy Directive

We are _not_ familiar with every specific act/legislation/law/directive/regulation, but our plugin could be useful if you need to display a cookie consent banner and/or block scripts conditionally.

Check out the [Configuration](https://github.com/pressidium/pressidium-cookie-consent/wiki/Configuration) section of our [wiki](https://github.com/pressidium/pressidium-cookie-consent/wiki) to learn more about how to configure the plugin to handle user consents, store consent records, block scripts conditionally, etc.

Geo-blocking/DNT
---

- **Geo-blocking:** This is not a functionality supported by our plugin
- **Do Not Track (DNT):** [This is deprecated](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/doNotTrack)

---

I’m closing this issue as resolved. If, however, you have any further questions, feel free to [open another issue](https://github.com/pressidium/pressidium-cookie-consent/issues/new) 🙂
