### ISSUE TITLE
Issue Report: Excessive API Calls to /wp-json/pressidium-cookie-consent/v1/consent Endpoint

### ISSUE THREAD

**Issue by Nesh1988** [pressidium/pressidium-cookie-consent#74]
Hello,

We are experiencing an issue with the Pressidium Cookie Consent plugin on our WordPress website. The plugin is making an excessive number of API calls to the endpoint /wp-json/pressidium-cookie-consent/v1/consent, which is severely impacting our server performance.

Our current plugin configuration is as follows:

Re-Consent: Enabled
Cookie Expiration: 182 days
Auto-clear Cookies: Disabled
Page Scripts Management: Enabled
Bot Detection: Enabled
Delay for Consent Modal: 0 milliseconds
Google Consent Mode: Enabled
Ads Data Redaction: Disabled
URL Passthrough: Disabled
Despite these settings, we have recorded over 84,000 calls to this endpoint, leading to high CPU load and significant performance degradation.

Update: the endpoint returns 404

**Comment by over-engineer** [comment]
Hey, @Nesh1988!

>The plugin is making an excessive number of API calls to the endpoint /wp-json/pressidium-cookie-consent/v1/consent

Whenever a user updates their consent, including the first time they consent, an API call is sent to the `POST /wp-json/pressidium-cookie-consent/v1/consent` endpoint to record it.

>we have recorded over 84,000 calls to this endpoint

* Does the number of API calls align with the traffic your website receives?

* Roughly how many consents have been recorded so far? You can check this by going to wp-admin → Cookie Consent → Consent Records.

>Are there any known issues or bugs related to the /wp-json/pressidium-cookie-consent/v1/consent endpoint that might be causing this behavior?

No issues related to the `POST /wp-json/pressidium-cookie-consent/v1/consent` endpoint have been reported.

>What recommendations do you have to further optimize the plugin settings to reduce the frequency of these requests?

A potential workaround is to turn off the “Record consents” setting. Head to wp-admin, choose the “General” tab, and disable the “Record Consents” option under the “Configuration” section.

**Comment by Nesh1988** [comment]
Thanks for your time @over-engineer 

The traffic for July so far is 17k users and 87k views and 215k event count according to analytics. In the consent records, there are 26767 items. Thanks for the suggestion, I will try it.

**Comment by over-engineer** [comment]
There hasn’t been any activity on this issue for a while, so I’ll close it as resolved. Feel free to reopen it at any time.
