### ISSUE TITLE
Plugin ignore options

### ISSUE THREAD

**Issue by Nobe-san** [pressidium/pressidium-cookie-consent#78]
After added reopen button to consent, plugin start ignoring options. Plugin delete choises from frontend. In console is zero errors.
![image](https://github.com/user-attachments/assets/f0baf17a-4cd6-487b-8de6-b12df0a906a3)

**Comment by over-engineer** [comment]
Hey, @Nobe-san!

>After added reopen button to consent, plugin start ignoring options. Plugin delete choises from frontend.

It seems like you’ve selected the “Hide empty categories” option, though no cookies are currently set under the “Cookies” tab.

Typically, you need to list the cookies your website sets in the “Cookies” tab for features like “Auto-clear cookies” to function correctly. Alternatively, you could turn off the “Hide empty categories” under the “General” tab.

If that’s not the case, please provide your settings, if possible.

To export your settings as a JSON file:

1. Log in to wp-admin
2. Navigate to “Cookie Consent”
3. Scroll to the bottom of the settings page
4. Click “Export Settings”

**Comment by Nobe-san** [comment]
oh ok so this is new feature i was look at websites which have older version and there is no such option like this. Ok understand. We are not using tab Cookies and before its was hide when you dont translate text for headers. But ok thank you, i will change it on our websites.
