### ISSUE TITLE
Missing Google Ads data in Google Analytics 4

### ISSUE THREAD

**Issue by Earntor** [pressidium/pressidium-cookie-consent#87]
Hello,

I have noticed that there is a big discrepancy between our google ads clicks and the CPC data in google analytics 4. I know there are many factors that could influence this, such as ad blockers, cookie banner, etc. But in our case this difference is 50%. In other words, we only see 50% of the total google ads clicks in our GA4. Is it possible that our cookie banner (code) or GTM code is not in the right order? 
Website: houtvanuwvloer.nl

This is the CPC in GA4: 
![image](https://github.com/user-attachments/assets/4a54bff2-6206-4277-bfe6-85d32886bd14)

And this is the Google Ads clicks:
![image](https://github.com/user-attachments/assets/679553a0-dda7-471f-a1a4-3fbcf3c527e3)

Or is there any additional information you need from me?

Thanks in advance!

**Comment by over-engineer** [comment]
Hey, @Earntor!

Have you enabled the Google Consent Mode integration?

If you haven’t, follow these steps to enable it:

1. Log in to your WordPress admin dashboard (wp-admin)
2. Navigate to “Cookie Consent”
3. Select the “Consent Mode” tab
4. Switch on “Google Consent Mode v2 (GCM)”

Integration options include Google tag (gtag.js) or Google Tag Manager (GTM).

Additionally, you could try enabling the “URL passthrough” option — an optional feature, which passes information in URLs, and can be used to send event and session-based analytics across pages without cookies.

You can learn more about URL passthrough at https://developers.google.com/tag-platform/security/guides/consent?consentmode=advanced#passthroughs.

**Comment by over-engineer** [comment]
Hey, @Earntor!

As there hasn't been any activity on this topic for a while, I'll mark it as resolved.

If anything else comes up, feel free to reopen it or open a new one 🙂
