### ISSUE TITLE
Undefined array key "font"

### ISSUE THREAD

**Issue by JariRengeling97** [pressidium/pressidium-cookie-consent#88]
I did update the plug-in and now we get following error on every page:

```
Undefined array key "font"
public_html/web/app/plugins/pressidium-cookie-consent/includes/Client/Cookie_Consent.php:209
```

**Comment by over-engineer** [comment]
Hey, @JariRengeling97!

Thanks for spotting that issue. We appreciate the time you took to report this.

This was fixed in `1.5.3`, which was just released on the Plugin Directory 🎉

I’m closing this issue as resolved. Please feel free to reopen it, if there’s anything I overlooked.
