### ISSUE TITLE
Pressidium cookie consent plugin - `wp-json/pressidium-cookie-consent/v1/consent` 500 (Internal Server Error)

### ISSUE THREAD

**Issue by michael121-tech** [pressidium/pressidium-cookie-consent#92]
Hi all,

using the pressidium cookie consent plugin the first time an see a 500 (Internal Server Error):

Request URL:
https://xxxx/wp-json/pressidium-cookie-consent/v1/consent
Request Method:
POST
Status Code:
500 Internal Server Error
Remote Address:
xxxxx:443
Referrer Policy:
strict-origin-when-cross-origin

cache-control:
no-cache, must-revalidate, max-age=0
content-type:
application/json; charset=UTF-8

date:
Mon, 09 Sep 2024 15:01:44 GMT
expires:
Wed, 11 Jan 1984 05:00:00 GMT
server:
nginx
strict-transport-security:
max-age=15768000; includeSubDomains
x-powered-by:
PHP/8.1.29

:authority:
xxxxx
:method:
POST
:path:
/wp-json/pressidium-cookie-consent/v1/consent
:scheme:
https
accept:
*/*
accept-encoding:
gzip, deflate, br, zstd
accept-language:
de-DE,de;q=0.9
authorization:
Basic xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
content-length:
371
content-type:
application/json;charset=UTF-8
cookie:
pressidium_cookie_consent={"categories":["preferences"],"level":["preferences"],"revision":3,"data":null,"rfc_cookie":false,"consent_date":"2024-09-09T15:01:49.117Z","consent_uuid":"bfee4638-324e-4bbf-914f-xxxxxxxxxxxxxxxx","last_consent_update":"2024-09-09T15:01:49.117Z"}
origin:
https://xxxxxxxxxxxxxxxx
priority:
u=1, i
referer:
https://xxxxxxxxxxxxxxxxxxxxx/
sec-ch-ua:
"Chromium";v="128", "Not;A=Brand";v="24", "Google Chrome";v="128"
sec-ch-ua-mobile:
?1
sec-ch-ua-platform:
"Android"
sec-fetch-dest:
empty
sec-fetch-mode:
cors
sec-fetch-site:
same-origin
user-agent:
Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Mobile Safari/537.36

I would be happy to get an idea how to fix it.

Thanks in advance!

Michael

**Comment by over-engineer** [comment]
Hey, @michael121-tech!

* Are there any related error logs on your server?
* Would you mind sharing your configuration?

---

To export your settings as a JSON file:

1. Log in to wp-admin
2. Navigate to “Cookie Consent”
3. Scroll to the bottom of the settings page
4. Click “Export Settings”

**Comment by over-engineer** [comment]
Hey, @michael121-tech!

As there hasn't been any activity on this topic for a while, I'll mark it as resolved.

If anything else comes up, feel free to reopen it or open a new one 🙂
